# Generated by Django 4.2.17 on 2025-02-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_recipe_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instruction',
            new_name='instructions',
        ),
    ]
