# Generated by Django 4.2.17 on 2025-02-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_instruction_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
