# Generated by Django 4.2.17 on 2025-02-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_feat_image_recipe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
